- package.json
- src/form/input/typeahead/TypeaheadInput.tsx
- src/select/typeahead/TypeaheadSelect.tsx
- To control the value of `TypeaheadInput`'s value we needed to enable controlled value passing
> fix: Make TypeaheadInput Value Controlled

- package.json
- src/form/field/_form-field.scss
- Initial `font-size` and `font-weight` is not necessary since we switched to CSS variables
> fix(form-field): Remove unnecessary properties

- package-lock.json
- src/core/utils/domUtils.ts
- src/dropdown/Dropdown.tsx
- src/dropdown/_dropdown.scss
- src/dropdown/list/DropdownList.tsx
- src/dropdown/list/_dropdown-list.scss
- src/dropdown/list/item/DropdownListItem.tsx
- src/ui/reference/_measurement.scss
- `document.hidden` is used on dropdown focus and blur handlers to handle changes on screen visibility correctly
- Instead of toggling the whole dropdown menu from DOM, we now use CSS to handle its visibility
- Effect that listens `selectOption` to focus on it is removed and now we only use `focusedOption` to handle scroll computations
- Direct DOM access to the focused list item element is removed to use React Ref API.
- Nesting of `dropdown-header-button` CSS block is removed
> fix(dropdown): Improvements on styles and handle menu visibility via CSS

- README.md
- package-lock.json
- package.json
- rollup.config.js
- src/button/_button.scss
- src/dropdown/_dropdown.scss
- src/dropdown/list/_dropdown-list.scss
- src/dropdown/list/item/_dropdown-list-item.scss
- src/form/field/_form-field.scss
- src/form/field/message-row/_form-field-message-row.scss
- src/form/input/_input.scss
- src/form/input/checkbox/_checkbox.scss
- src/form/input/file/_file-input.scss
- src/form/input/radio/_radio.scss
- src/index.ts
- src/select/typeahead/_typeahead-select.scss
- src/tag/_tag.scss
- With `0.3.0` we're requiring to import the `main.css` to use initial styles 
- Removed unused imports to reduce the bundle size
Resolves https://github.com/Hipo/react-ui-toolkit/issues/30
> fix: Export `main.css` instead of inline styles

- src/select/typeahead/TypeaheadSelect.tsx
- We've `canOpenDropdownMenu` prop to lock the menu but `TypeaheadSelect` doesn't uses this. So, I've added a tiny check to `handleTypeaheadInputFocus`
> fix(typeahead/select): Use `canOpenDropdownMenu`

- src/form/input/typeahead/TypeaheadInput.tsx
- src/select/typeahead/TypeaheadSelect.tsx
- stories/5-Typeahead.stories.tsx
**`TypeaheadInput` component**
- new `initialValue` prop added and it defaults to empty string.
- when `value` prop is present and it has a string value, this means that TypeaheadInput's value is held as a state in the parent and should be controlled by the parent as well. So whenever value changes and it has a string value then we update the TypeaheadInput's state. TypeaheadInput still controls its own state as it has to deal with debouncing.
- Removes `shouldResetValue` prop.
**`TypeaheadSelect` component**
- `typeaheadProps` prop is updated to have the following type: `Pick<TypeaheadInputProps, "id" | "placeholder" | "name" | "onFocus">`. Note how you cannot pass `value` under this object any longer.
- new `initialKeyword` prop added and it defaults to empty string.
- TypeaheadSelect …
> fix(typeahead-select): Improves the handling of controlled keyword state

- src/dropdown/list/item/DropdownListItem.tsx
- src/dropdown/list/item/_dropdown-list-item.scss
- stories/1-Dropdown.stories.tsx
- stories/utils/constants/_dropdown-story-option-constants.scss
- stories/utils/constants/dropdownStoryOptionConstants.tsx
- Dropdown subtitle CSS class has `font-size` properties smaller than the title class.
- Dropdown samples have separated as `States`, `No Options`, `Pending Request`, `Disabled`.
- Dropdown Menu with icon
- Dropdown options with subtitle
- Dropdown with customized options
- https://github.com/Hipo/react-ui-toolkit/issues/50
> feat(dropdown): Add samples with icon/subtitle/context/menu

- src/form/input/file/_file-input.scss
- Sets the file input container position as `relative` to prevent positioning related bugs (because `.file-input` child is `absolute` positioned)
> fix(file-input): Set file input container as relative positioned

- .github/workflows/new-version.yml
I created a new npm account for GitHub actions: [hipo-web-bot](https://www.npmjs.com/~hipo-web-bot)
_~~I will add it's API key to the repo secrets, once it is added to the `@hipo` organization on npm~~_
`NPM_TOKEN` was added to the repo by @mucahit . This is ready to merge
> build: Add GH workflows for automating npm publish and tagging on github

- package.json
- src/core/utils/time/timeTypes.ts
- src/countdown/util/countdownTypes.ts
- src/index.ts
- tsconfig.json
- `--isolatedModules` flag was added.
- Prop export type was changed.
```
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
```
> fix(core): Add `--isolatedModules` flag

- src/form/input/Input.tsx
- src/form/input/typeahead/TypeaheadInput.tsx
- src/select/typeahead/TypeaheadSelect.tsx
- stories/5-Typeahead.stories.tsx
- `typeaheadProps` can use all input types.
> feat(typeahead): Add type prop for TypeaheadInput

- .storybook/config.js
- src/toast/Toast.tsx
- src/toast/ToastProvider.tsx
- src/toast/util/toastConstants.ts
- src/toast/util/toastReducer.ts
- src/toast/util/toastTypes.ts
- stories/8-Toast.stories.tsx
Some projects might want Toasts to not autoClose by default. This adds a prop to ToastProvider that allows this functionality. You can still pass `autoClose: true` with `toast.display` callback to override ToastProvider's autoCloseToasts prop value.
> fix(toast-provider): Allow control of autoClose via ToastProvider

- package-lock.json
- package.json
- src/form/input/Input.tsx
- src/toast/Toast.tsx
- Add `toast` container class
- Add `input-container--type-number` container class for `number input`
> fix: Add missing classnames to Toast and Input

- src/core/utils/number/numberTypes.ts
- src/core/utils/number/numberUtils.ts
- src/form/input/Input.tsx
- stories/0-Form.stories.tsx
- `numberFormatter` utility was added again.
- Input can have negative numbers with a minus sign.
- If the input has one of `shouldFormatToLocaleString`, `maximumFractionDigits` props or value is negative, can't have leading zeros. Also, if the first character of the value is a minus sign, the user can not type zero.
```
Leading zero: 0250 -> 250
Negative zero: -0 -> -  // If maximumFractionDigits is 0
Double leading zero: 00 -> 0 
```
> fix(number-input): Localization improvements

- src/button/Button.tsx
- src/button/file-upload/FileUploadButton.tsx
- src/form/input/file/FileInput.tsx
- stories/3-Button.stories.tsx
- `ref` prop was added for can pass `ref` and use with `useRef` hook.
- It doesn't contain breaking change.
- It can be used like this;
```ts
const buttonRef = useRef<HTMLButtonElement | null>(null);
<Button ref={buttonRef} {...props} />
```
> feat(button): Add `ref` prop

- src/form/input/Input.tsx
- src/form/input/input.test.tsx
Add Input tests with number type 
- Localization 
- `maximumFractionDigits` consistency
- Removing leading zero 
- Entering letter 
- Converting scientific notation  
- Formatting locale string
> feat(input): Add input tests with number type

- src/progress-bar/ProgressBar.tsx
- ProgressBar expects Component style as prop. It is already defined as default below. It should be optional
- Made style prop optional
> fix(progress-bar): Update ProgressBar component props

- src/button/Button.tsx
- src/dropdown/Dropdown.tsx
- src/form/password-input/PasswordInput.tsx
- Changed forwardRef types.
- Removed explicit prop type in the component definition.
```diff
- const Button = React.forwardRef<HTMLButtonElement, Record<string, any>>(
+ const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
-  function ButtonComponent(props: ButtonProps, ref) {
+  function ButtonComponent(props, ref) {
```
-  Fixed incompatible types in the `Dropdown` component
```
Types of property ''aria-haspopup'' are incompatible.
Type '"listbox" | "menu" | "combobox"' is not assignable to type 'boolean | "listbox" | "menu" | "dialog" | "false" | "true" | "tree" | "grid" | undefined'.
Type '"combobox"' is not assignable to type 'boolean | "listbox" | "menu" | "dialog" | "false" | "true" | "tree" | "grid" | undefined'.
```
- Fixed typo in the `passwordInput` component. …
> fix(button): Fix prop types

- src/button/file-upload/FileUploadButton.tsx
- src/form/input/file/FileInput.tsx
- forwardRef types changed
- Duplicated types removed on `FileUploadButton`
> fix: FileInput and FileUploadButton prop types

- src/form/input/file/FileInput.tsx
- `isMultiple` prop passed to input element's `multiple` attribute to allow multiple file upload
> feat(file-input): Allow multiple file upload

- package-lock.json
- package.json
- src/list/List.tsx
- src/list/util/listUtils.ts
- stories/8-List.stories.tsx
- Install `uuid` package to generate unique IDs.
- If not provided `listItemKeyGenerator` or `testid` props, generates uuid. 
- Also, generating a key with `testid` is not best practice. Because if list manipulate (add/remove an item or changing order) causes using wrong keys.
> fix(list): Add uuid for each list item

- package-lock.json
- src/index.ts
- src/toast/Toast.tsx
- src/toast/ToastProvider.tsx
- src/toast/stack/ToastStack.tsx
- src/toast/util/toastHooks.ts
-  In our apps, we mostly only care Toast state `dispatch` function. But in the current implementation, since `useToaster` returns both state and dispatch in the same object, dispatch function will "change" on every state change, and this will cause re-render in the components that use `dispatch`.
- Separating state and dispatch contexts, so that state changes won't trigger a change in `dispatch`
I tried on my local with `npm-link`, here is the result:
https://user-images.githubusercontent.com/22727931/175345592-35eadfd1-6b05-4a3d-9334-7320a0e95f32.mov
Only necessary elements re-renders. As expected.
**If the app is only using `useToaster`, it won't be a breaking change and won't require any changes on the project**
> refactor(toast): Fix unnecessarily re-rendering all children of toast context on every state change

- rollup.config.js
This was causing error while building. I guess we decided to change the folder name but forgot to update the rollup config.
Will merge right now since it's a straightforward path fix.
> fix(build): fix timeinput component path in rollup config

- .github/workflows/pr-preview.yml
- package-lock.json
- package.json
In case of a change of PR (including opening a new PR), this new workflow automatically:
- Builds storybook and deploys it to GitHub Pages
- It uses `gh-pages` branch for deployments
- Posts a link of preview build to PR
- Example link: https://jamcry.github.io/react-ui-toolkit/pr-preview/pr-3/
- After PR is closed, it removes the build files, and updates the comment of the PR
- Uses: [rossjrw/pr-preview-action@v1](https://github.com/rossjrw/pr-preview-action)
- Check my forked repo for example: https://github.com/jamcry/react-ui-toolkit
- The main reason why we wanted this kind of solution is to be able to test new changes before sending it to production.
> build: Add a new workflow that deploys PR previews

- src/tab/Tab.tsx
> fix(tab):id attribute added to tab wrapper

- .github/workflows/new-version.yml
- .github/workflows/pr-preview.yml
- README.md
- package-lock.json
- package.json
As discussed with @jamcry, we decided to update the gh-workflows as well
- Updated the `babel-loader` to the latest, since it was giving a CI/CD error on `storybook` configurations.
> Update node versions for github workflows

- src/tab/Tab.tsx
- src/tab/header/item/TabHeaderItem.tsx
- stories/12-Tab.stories.tsx
> fix(tab):generic id type added to TabItem
