studiobakers/react-ui-toolkit

src/tab/Tab.tsx
src/tab/_tab.scss
src/tab/header/item/TabHeaderItem.tsx
stories/6-Tab.stories.tsx

- Basic implementation of Tab component

feat(tab): Add Tab Component

---

.stylelintrc
README.md
package-lock.json
package.json
src/button/_button.scss
src/dropdown/_dropdown.scss
src/dropdown/list/_dropdown-list.scss
src/dropdown/list/item/_dropdown-list-item.scss
src/form/field/message-row/_form-field-message-row.scss
src/form/input/_input.scss
src/form/input/checkbox/_checkbox.scss
src/form/input/file/_file-input.scss
src/form/input/radio/_radio.scss
src/select/typeahead/_typeahead-select.scss
src/tab/Tab.tsx
src/tab/_tab.scss
src/tab/header/item/TabHeaderItem.tsx
src/tag/_tag.scss
src/ui/reference/_colors.scss
src/ui/reference/_measurement.scss
stories/6-Tab.stories.tsx

chore: Switch to CSS Variables

---

package.json
src/button/_button.scss
src/ui/reference/_colors.scss

- Removed default `font-size` 
- Converted `color` to CSS Variable

chore(button): Improvements on Button styling

---

package-lock.json
package.json
src/select/typeahead/TypeaheadSelect.tsx

- Enabled `onFocus` prop for `typeaheadProps`

fix(select/typeahead): Enable `onFocus` Prop

---

package.json
src/index.ts
src/tab/Tab.tsx
src/tab/_tab.scss

- Exported forgotten Tab component and its types
- Minor fix on CSS

fix: Export Tab Component

---

src/index.ts

- Export `DropdownOption`, `DropdownOptionSelectHandler `, `DropdownSelectedOption ` interfaces on index

fix(dropdown): Export `DropdownOption`

---

src/form/input/_input.scss
src/ui/reference/_measurement.scss

This change will enable us to update border-radius without overriding CSS.

fix(input): Dynamize input border width.

---

src/tab/Tab.tsx
src/tab/header/item/TabHeaderItem.tsx

- Added a className to active `TabHeaderItem`

fix(tab): Add `active` className

---

README.md
src/form/field/FormField.tsx
src/form/field/message-row/FormFieldMessageRow.tsx
src/form/input/Input.tsx
src/form/input/checkbox/Checkbox.tsx
src/form/input/radio/Radio.tsx
src/form/input/radio/group/RadioGroup.tsx
src/list/List.tsx

- Resolves #28
- Resolves #35 
- Resolves #40
- Resolves #42 
- Resolves #43

chore: General Improvements

---

src/dropdown/Dropdown.tsx
src/select/typeahead/TypeaheadSelect.tsx
src/select/typeahead/_typeahead-select.scss
stories/5-Typeahead.stories.tsx

feat(typeahead/select): Add a class when there are selectedOptions

---

src/form/input/Input.tsx
stories/0-Form.stories.tsx

- https://github.com/Hipo/react-ui-toolkit/issues/56

fix(input): Add type prop for color picker

---

src/select/typeahead/TypeaheadSelect.tsx

feat(typeahead/select): Remove tags with Backspace key

---

rollup.config.js
src/index.ts
src/progress-bar/ProgressBar.tsx
src/progress-bar/_progress-bar.scss
stories/9-ProgressBar.stories.tsx

- https://github.com/Hipo/react-ui-toolkit/issues/68

feat(progress-bar): Add ProgressBar Component

---

.eslintignore
.eslintrc.js
rollup.config.js
src/countdown/util/countdownUtils.ts
src/form/textarea/Textarea.tsx
src/progress-bar/ProgressBar.tsx

- Some eslint rule violations were ignored.
- `"react/jsx-handler-names"` rule was added to `.eslintrc`.
- `.eslintrc` was added to `.eslintignore`.

fix(root): Fix eslint issues

---

package.json
src/index.ts

- Generic types were added to define in project scope.

fix(core): Add generic types that exported props

---

src/form/input/radio/RadioInput.tsx
src/form/input/radio/group/RadioGroup.tsx
src/index.ts

- Added generic type with default type to functional component
- Removed default generic type from prop interface
- Updated type definitions on 'index.ts'
Closes #57

fix(radioInput): Fix type of generic props

---

src/tab/Tab.tsx
src/tab/header/item/TabHeaderItem.tsx
src/tab/header/item/_tab-header-item.scss
stories/6-Tab.stories.tsx

- Optional `isDisabled` attribute added to TabItem.
- Created style for disabled TabItem.
- Added disabled state of TabItem to story page.
Closes #101

feat(tab): Add isDisabled attribute to TabItem

---

src/tab/Tab.tsx
src/tab/tab.test.tsx

- I'm not sure if test cases is enough or implemented correctly. I'm open for suggestions.

feat(tab): Add tests

---

README.md

- Replace storybook build command with the correct one

chore(readme): fix storybook script name

---

src/form/input/typeahead/TypeaheadInput.tsx
src/form/input/typeahead/typeahead-input.test.tsx

[Related Issue](https://github.com/Hipo/react-ui-toolkit/issues/220)

fix(typeahead): Make sure to pass all props to Input component

---

.github/workflows/pr-preview.yml

Fixes pr preview action failures by adding required action permissions

Update pr-preview.yml to add required permissions
